import Header from '@/components/Header'
import './globals.css'
import AuthContext from '@/context/AuthContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full max-w-screen-xl overflow-auto mx-auto'>
        <AuthContext>
          <Header />
          <section>{children}</section>
        </AuthContext>
      </body>
    </html>
  )
}
